language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
services: redis
before_script:
  - cd test/dummy && RAILS_ENV=test bundle exec rake db:migrate && cd -
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails41.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails50.gemfile
